<?php
include('dbcon.php');

// Fetch data from the 'plants' database
$plantsData = $database->getReference('plants')->getValue();

// Initialize arrays to store occupied bay and nft values
$occupiedBay = [];
$occupiedNft = [];

// Check if $plantsData is not null and is an array or object
if (!is_null($plantsData) && (is_array($plantsData) || is_object($plantsData))) {
    // Loop through the fetched data from 'plants' database to populate the occupied bay and nft arrays
    foreach($plantsData as $key => $row) {
        if ($row['plant_status'] === 'Planted') {
            $occupiedBay[] = $row['bay'];
            $occupiedNft[$row['bay']][] = $row['nft']; // Group occupied NFTs by bay
        }
    }
}

// Fetch all available bay and placement values from the 'BAY' database
$allBayData = $database->getReference('BAY')->getValue();

// Initialize arrays to store available bay and nft options
$availableBay = [];
$availableNft = [];

// Loop through the allBayData and filter available bay and nft options
foreach($allBayData as $bay) {
    // Check if the bay is not occupied or if there are available nft values associated with the bay
    if (!in_array($bay['bay'], $occupiedBay) || !isset($occupiedNft[$bay['bay']]) || !in_array($bay['placement'], $occupiedNft[$bay['bay']])) {
        $availableBay[] = $bay['bay'];
        $availableNft[$bay['bay']][] = $bay['placement']; // Group available NFTs by bay
    }
}
?>

<!-- Rest of the code remains unchanged -->


<!-- Modal -->
<div class="modal fade" id="addplants" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form id="plantForm" class="row g-3" method="POST" action="code.php" enctype="multipart/form-data">


                    <div class="col-md-12">
                        <div class="pic">
                            <img src="pics/default.png" id="profile-pic" alt="Plant Preview">
                        </div>
                    </div>


                    <div class="col-md-12">
                        <label for="photo" class="form-label">Plants Photo</label>
                        <input type="file" class="form-control" name="plant_photo" id="plant_photo" accept="image/*" onchange="displayImagePreview()" required>
                    </div>


                    <div class="col-md-12">
                        <label for="selectPlant" class="form-label">Name of Plant<span style="color: red;"> *</span></label>
                        <select class="form-select" aria-label="Name of Plant" id="plant_name" name="plant_name">
                            <option value="" selected disabled>Select Plant Name</option>
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label for="pHLevel" class="form-label">Lowest pH Level</label>
                        <input type="text" name="ph_lvl_low" class="form-control" id="ph_lvl_low" placeholder="generated by the system" required readonly>
                    </div>

                    <div class="col-md-6">
                        <label for="pHLevel" class="form-label">Highest pH Level</label>
                        <input type="text" name="ph_lvl_high" class="form-control" id="ph_lvl_high" placeholder="generated by the system" required readonly>
                    </div>


                    <div class="col-md-6">
                        <label for="selectBay" class="form-label">Bay<span style="color: red;"> *</span></label>
                        <select class="form-select" name="bay" id="selectBay" required onchange="updateNFTOptions()">
                            <option selected disabled>Select</option>
                            <?php
                            // Remove duplicates from availableBay array
                            $uniqueBays = array_unique($availableBay);
                            foreach ($uniqueBays as $bay) {
                                echo '<option value="' . $bay . '">' . $bay . '</option>';
                            }
                            ?>
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label for="selectPipe" class="form-label">Placement<span style="color: red;"> *</span></label>
                        <select class="form-select" name="nft" id="selectPipe" required disabled>
                            <option selected disabled>Select</option>
                        </select>
                    </div>

                    <div class="col-md-12">
                        <label for="datePlanted" class="form-label">Date Planted<span style="color: red;"> *</span></label>
                        <input type="date" class="form-control" id="date_planted" name="date_planted" placeholder="Date Planted" required />
                    </div>

                    <div class="col-md-12">
                        <label for="estimatedHarvestDate" class="form-label">Estimated Harvest Date</label>
                        <input type="date" class="form-control" id="date_harvest" name="date_harvest" placeholder="generated by the system" required readonly />
                    </div>

                    <div class="modal-footer d-flex justify-content-end align-items-center mt-3">
                        <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-dismiss="modal" style="background-color: white; border: 1px solid #8f8f8f; border-radius: 10px; box-shadow: none; color: black;">Cancel
                        </button>
                        <button type="submit" class="btn btn-primary" data-mdb-ripple-init name="add-plant-btn" style="background-color: #2C3090; box-shadow: none;">Add Plant
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteplants" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form class="form-horizontal" method="POST" action="code.php">
                    <input type="hidden" class="plantid" name="id">
                    <div class="text-center">
                        <p>Are you sure you want to delete this plant?</p>
                        <h2 class="bold" id="delete_plant_name" name="plant_name"></h2>
                    </div>
            </div>
            <div class="modal-footer d-flex justify-content-end align-items-center mt-3">
                <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-dismiss="modal" style="background-color: white; border: 1px solid #8f8f8f; border-radius: 10px; box-shadow: none; color: black;">NO</button>
                <button type="submit" class="btn btn-danger" name="delete-plants-btn" style="border-radius: 10px; box-shadow: none; color: white;">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function updateNFTOptions() {
        var selectedBay = document.getElementById('selectBay').value;
        var availableNft = <?php echo json_encode($availableNft); ?>;
        var nftDropdown = document.getElementById('selectPipe');

        // Clear existing options
        nftDropdown.innerHTML = '<option selected disabled>Select</option>';

        // Add filtered available NFTs for the selected bay
        availableNft[selectedBay].forEach(function(nft) {
            var option = document.createElement('option');
            option.value = nft;
            option.text = nft;
            nftDropdown.add(option);
        });

        // Enable the NFT dropdown
        nftDropdown.disabled = false;

        // Automatically select the first option
        if (nftDropdown.options.length > 1) {
            nftDropdown.selectedIndex = 1; // Select the first available NFT option
        }
    }
</script>
